// Code generated by "stringer -type=Category"; DO NOT EDIT

package mind

import "fmt"

const _Category_name = "UnknownArtistActorBookDateMovieMusicPersonPlaceSerieVideoVideoGameFood"

var _Category_index = [...]uint8{0, 7, 13, 18, 22, 26, 31, 36, 42, 47, 52, 57, 66, 70}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return fmt.Sprintf("Category(%d)", i)
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
