// Code generated by "stringer -type=Category"; DO NOT EDIT

package mind

import "fmt"

const _Category_name = "UncategorizedArtistActorBookDateMovieMusicPersonPlaceSerieVideoVideoGameFood"

var _Category_index = [...]uint8{0, 13, 19, 24, 28, 32, 37, 42, 48, 53, 58, 63, 72, 76}

func (i Category) String() string {
	if i < 0 || i >= Category(len(_Category_index)-1) {
		return fmt.Sprintf("Category(%d)", i)
	}
	return _Category_name[_Category_index[i]:_Category_index[i+1]]
}
